sudo: false

language: python
python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest nomkl scipy=0.18.1 numpy=1.11.2 pandas=0.18.0 matplotlib
  - conda env update -f environment.yml
  - conda install -n test-environment numba
  - source activate test-environment
  - python setup.py install


# command to run tests, e.g. python setup.py test
script:
  - cd ogusa; py.test -s -v -m 'not full_run'
