sudo: false

language: python
python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n ospcdyn python=$TRAVIS_PYTHON_VERSION
  - source activate ospcdyn
  - conda env update -f environment.yml
  - python setup.py install
  - travis_wait mvn install
  

# command to run tests, e.g. python setup.py test
script:
  - cd ogusa; py.test -s -v -m 'not full_run and not regression'
