package:
  name: ogusa
  version: 0.0.0

source:
  path: ..

requirements:
  build:
    - python=3.6
    - taxcalc
    - setuptools
    - scipy
    - matplotlib
    - dask

  run:
    - python=3.6
    - taxcalc
    - setuptools
    - scipy
    - matplotlib
    - dask

about:
  home: https://github.com/open-source-economics/OG-USA/

test:
  imports:
    - ogusa
    - ogusa.SS
    - ogusa.TPI
    - ogusa.demographics
    - ogusa.elliptical_u_est
    - ogusa.firm
    - ogusa.fiscal
    - ogusa.get_micro_data
    - ogusa.household
    - ogusa.income
    - ogusa.labor
    - ogusa.macro_output
    - ogusa.parameters
    - ogusa.tax
    - ogusa.txfunc
    - ogusa.utils
