package:
  name: ogusa
  version: 0.5.10

requirements:
  build:
    - python
    - pip

  run:
    - matplotlib
    - numpy >=1.12.1
    - pandas >=0.20.1
    - pytest
    - python
    - scipy
    - setuptools
    - taxcalc
    - dask

about:
  home: https://github.com/open-source-economics/OG-USA/

test:
  imports:
    - ogusa
    - ogusa.SS
    - ogusa.TPI
    - ogusa.calibrate
    - ogusa.demographics
    - ogusa.elliptical_u_est
    - ogusa.firm
    - ogusa.fiscal
    - ogusa.get_micro_data
    - ogusa.household
    - ogusa.income
    - ogusa.labor
    - ogusa.macro_output
    - ogusa.parameters
    - ogusa.tax
    - ogusa.txfunc
    - ogusa.utils
    - ogusa.wealth
    - ogusa.wealthinit
